local HubLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/ui-rbx-designs/UI-Designs/refs/heads/main/libraries/oxcure-lib.lua"))()
                      -- title        menu keybind
local Hub = HubLib.new("Oxcure Hub", Enum.KeyCode.K)
local Fighting = Hub:Page("Combat",   "sword")
local fightTab = Fighting:Tab("Aimbot")

fightTab:Section("Aimbot")
fightTab:Toggle("Aimbot", false, function(v)
	print("Aimbot:", v)
end)
fightTab:Toggle("Team Check", true, function(v)
	print("Team Check:", v)
end)
fightTab:Toggle("Show FOV", true, function(v)
	print("Show FOV:", v)
end)
fightTab:Slider("FOV Size", 50, 400, 200, "px", function(v)
	print("FOV Size:", v)
end)
fightTab:Slider("Smoothing", 1, 10, 5, "", function(v)
	print("Smoothing:", v)
end)
fightTab:Section("Targeting")
fightTab:Dropdown("Target Part", {"Head","Torso","Nearest","Random"}, "Head", function(v)
	print("Target Part:", v)
end)
fightTab:ColorPicker("FOV Color", {"2563eb","10b981","ef4444","f59e0b","a855f7","ffffff"}, function(v)
	print("FOV Color:", v)
end)

local hitboxTab = Fighting:Tab("Hitbox")

hitboxTab:Section("Hitbox Expander")
hitboxTab:Toggle("Hitbox Expander", false, function(v)
	print("Hitbox Expander:", v)
end)
hitboxTab:Toggle("Team Check", true, function(v)
	print("Team Check:", v)
end)
hitboxTab:Slider("Hitbox Size", 1, 50, 12, "", function(v)
	print("Hitbox Size:", v)
end)
hitboxTab:Toggle("Visualize Hitbox", false, function(v)
	print("Visualize Hitbox:", v)
end)
hitboxTab:Dropdown("Overlay Mode", {"Heavy","Light","Off"}, "Heavy", function(v)
	print("Overlay:", v)
end)

local uiTab = Fighting:Tab("UI Tweaks")

uiTab:Section("Window")
uiTab:Toggle("Blur Background", false, function(v)
	print("Blur:", v)
end)
uiTab:Toggle("ESP Preview", true, function(v)
	print("ESP Preview:", v)
end)
uiTab:Toggle("Hide Name", false, function(v)
	print("Hide Name:", v)
end)
uiTab:Toggle("Auto Save Config", false, function(v)
	print("Auto Save:", v)
end)
uiTab:Section("Appearance")
uiTab:Dropdown("Overlay", {"Snow","Dark","None"}, "Snow", function(v)
	print("Overlay:", v)
end)
uiTab:Dropdown("Font", {"Builder Sans","Abbon","Default"}, "Builder Sans", function(v)
	print("Font:", v)
end)
uiTab:Slider("Background Opacity", 0, 100, 55, "%", function(v)
	print("Opacity:", v)
end)
uiTab:ColorPicker("Accent", {"2563eb","10b981","ef4444","f59e0b","a855f7"}, function(v)
	print("Accent:", v)
end)

local Visuals = Hub:Page("Visuals", "eye")
local espTab  = Visuals:Tab("ESP")

espTab:Section("Player ESP")
espTab:Toggle("Enable ESP", false, function(v)
	print("ESP:", v)
end)
espTab:Toggle("Show Boxes", true, function(v)
	print("Boxes:", v)
end)
espTab:Toggle("Show Names", true, function(v)
	print("Names:", v)
end)
espTab:Toggle("Show Health", false, function(v)
	print("Health:", v)
end)
espTab:Slider("Max Distance", 50, 1000, 500, "m", function(v)
	print("Distance:", v)
end)
espTab:ColorPicker("Box Color", {"2563eb","10b981","ef4444","f59e0b","ffffff"}, function(v)
	print("Box Color:", v)
end)

local chamsTab = Visuals:Tab("Chams")

chamsTab:Section("Chams")
chamsTab:Toggle("Enable Chams", false, function(v)
	print("Chams:", v)
end)
chamsTab:Toggle("Visible Only", true, function(v)
	print("Visible Only:", v)
end)
chamsTab:Dropdown("Chams Style", {"Flat","Neon","Glass","Outline"}, "Flat", function(v)
	print("Style:", v)
end)
chamsTab:Slider("Transparency", 0, 100, 30, "%", function(v)
	print("Transparency:", v)
end)
chamsTab:ColorPicker("Chams Color", {"2563eb","10b981","ef4444","f59e0b","a855f7"}, function(v)
	print("Chams Color:", v)
end)

local Settings = Hub:Page("Settings", "settings")
local settingsTab = Settings:Tab("General")

settingsTab:Section("Interface")
settingsTab:Toggle("Always on Top", true, function(v)
	print("Always on Top:", v)
end)
settingsTab:Toggle("Notifications", true, function(v)
	print("Notifications:", v)
end)
settingsTab:Dropdown("Theme", {"Dark","Darker","Midnight"}, "Dark", function(v)
	print("Theme:", v)
end)
settingsTab:Slider("UI Scale", 80, 130, 100, "%", function(v)
	print("Scale:", v)
end)
settingsTab:Section("Performance")
settingsTab:Toggle("Low Latency Mode", false, function(v)
	print("Low Latency:", v)
end)
settingsTab:Dropdown("Update Rate", {"High","Medium","Low"}, "High", function(v)
	print("Update Rate:", v)
end)

local configTab = Settings:Tab("Config")

configTab:Section("Config")
configTab:Dropdown("Load Config", {"Default","Config1","Config2","Config3"}, "Default", function(v)
	print("Load:", v)
end)
configTab:Toggle("Auto Load", false, function(v)
	print("Auto Load:", v)
end)
configTab:Toggle("Auto Save", false, function(v)
	print("Auto Save:", v)
end)
configTab:Section("Danger Zone")
configTab:Toggle("Reset on Spawn", false, function(v)
	print("Reset:", v)
end)

local Colors = Hub:Page("Colors", "palette")
local colorsTab = Colors:Tab("Accent Colors")

colorsTab:Section("Primary")
colorsTab:ColorPicker("Accent Color",  {"2563eb","10b981","ef4444","f59e0b","a855f7","ec4899"}, function(v)
	print("Accent:", v)
end)
colorsTab:ColorPicker("Text Color",    {"ffffff","dcdce8","aaaabc","888899"}, function(v)
	print("Text:", v)
end)
colorsTab:ColorPicker("Border Color",  {"27272f","3a3a48","4a4a58","55556a"}, function(v)
	print("Border:", v)
end)
colorsTab:Section("ESP Colors")
colorsTab:ColorPicker("Enemy Color",   {"ef4444","f97316","fbbf24"}, function(v)
	print("Enemy:", v)
end)
colorsTab:ColorPicker("Team Color",    {"10b981","22c55e","84cc16"}, function(v)
	print("Team:", v)
end)
colorsTab:ColorPicker("Box Color",     {"2563eb","7c3aed","db2777"}, function(v)
	print("Box:", v)
end)

local Config = Hub:Page("Config", "sliders-horizontal")
local cfgTab  = Config:Tab("Profiles")

cfgTab:Section("Profiles")
cfgTab:Dropdown("Active Profile", {"Default","Rage","Legit","HVH"}, "Default", function(v)
	print("Profile:", v)
end)
cfgTab:Toggle("Auto Save on Exit", true, function(v)
	print("Auto Save:", v)
end)
cfgTab:Toggle("Sync to Cloud", false, function(v)
	print("Sync:", v)
end)
cfgTab:Section("Import / Export")
cfgTab:Toggle("Pretty Print JSON", false, function(v)
	print("Pretty Print:", v)
end)
